[tool.flake8]
min_python_version = "3.8.0"
max_complexity = 10
max-line-length = 80
statistics = true
count = true
eradicate-aggressive = true

[tool.black]
line-length = 80
skip-string-normalization = true
target-version = ["py38", "py39", "py310"]
exclude = '''
/(
    \.pytest_cache
    \.mypy_cache
)/
'''

[tool.check-manifest]
ignore = [".gitignore"]
